---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-vm-cloudinit
type: Opaque
stringData:
  userdata: |
    #cloud-config
    user: cloud-user
    password: {{ randAlphaNum 16 }}
    chpasswd:
      expire: false
    runcmd:
      - yum install -y https://nginx.org/packages/centos/9/x86_64/RPMS/nginx-1.26.2-1.el9.ngx.x86_64.rpm
      - mkdir -p /mnt/data
      - semanage port -a -t http_port_t -p tcp 8080
      - semanage fcontext -a -t httpd_sys_content_t '/mnt/data(/.*)?'
      - restorecon -Rv /mnt/data
      - firewall-cmd --permanent --zone=public --add-port=8080/tcp
      - firewall-cmd --reload
      - mount /dev/$(lsblk --nodeps -no name,serial | grep CKCQKP | cut -f1 -d' ') /mnt/data
      - mount /dev/$(lsblk --nodeps -no name,serial | grep YLPKDF | cut -f1 -d' ') /etc/nginx
      - systemctl enable nginx
      - systemctl start nginx
