---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod
spec:
  selector:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

{{- if .Values.vm.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vm
spec:
  selector:
    vm.kubevirt.io/name: nginx-vm
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}