---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
    cdi.kubevirt.io/storage.usePopulator: 'true'
  name: web-assets
spec:
  pvc:
    accessModes:
      - ReadWriteMany
    storageClassName: managed-nfs-storage
    resources:
      requests:
        storage: 50Mi
  source:
    upload: {}


