---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-to-user-default-webserver
  namespace: virt-corp-image-builder
subjects:
- kind: ServiceAccount
  name: default
  namespace: webserver
roleRef:
  kind: ClusterRole
  name: datavolume-cloner 
  apiGroup: rbac.authorization.k8s.io
