---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: ab-example.my-project.my-domain
  to:
    kind: Service
    name: nginx-pod
    weight: 10
  alternateBackends:
  - kind: Service
    name: nginx-vm
    weight: 15