---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  host: nginx.<DOMAIN>
  tls: 
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx-vm
    weight: 100
  alternateBackends:
  - kind: Service
    name: nginx-pod
    weight: 100